In [59]:
# 导包
import time
import numpy as np
import pandas as pd
from sqlalchemy import create_engine
from pyecharts.charts import Bar3D              # 需要安装下, 即: pip install pyecharts
from pyecharts.commons.utils import JsCode
import pyecharts.options as opts

import os

In [60]:
# R:最近购买间隔， F:购买频次, M：钱

### 1. 加载数据

In [61]:
# 1.1 定义列表, 记录: Excel表名
sheet_names = ['2015', '2016', '2017', '2018', '会员等级']
# 1.2 从excel文件中读取数据, 获取到: 字典形式 -> {'2015': df对象, '2016': df对象, ...}
# 参1: Excel文件名(路径)
# 参2: Excel文件中的 表名
sheet_dict = pd.read_excel('./data/sales.xlsx', sheet_name=sheet_names)
sheet_dict

{'2015':               会员ID         订单号       提交日期    订单金额
 0      15278002468  3000304681 2015-01-01   499.0
 1      39236378972  3000305791 2015-01-01  2588.0
 2      38722039578  3000641787 2015-01-01   498.0
 3      11049640063  3000798913 2015-01-01  1572.0
 4      35038752292  3000821546 2015-01-01    10.1
 ...            ...         ...        ...     ...
 30769  39368100847  4281994827 2015-12-31   828.0
 30770       409757  4282010457 2015-12-31   199.0
 30771  38380526114  4282017675 2015-12-31   208.0
 30772     28074988  4282019440 2015-12-31    89.0
 30773  39460363230  4282025309 2015-12-31   719.0

 [30774 rows x 4 columns],
 '2016':               会员ID         订单号       提交日期     订单金额
 0      39288120141  4282025766 2016-01-01    76.00
 1      39293812118  4282037929 2016-01-01  7599.00
 2      27596340905  4282038740 2016-01-01   802.00
 3      15111475509  4282043819 2016-01-01    65.00
 4      38896594001  4282051044 2016-01-01    95.00
 ...            ...         ...        ...      ...
 41273  35336052906  4324910145 2016-12-31    99.00
 41274  39305835721  4324910148 2016-12-31   238.89
 41275  39296945352  4324910770 2016-12-31   765.00
 41276  14791026234  4324911025 2016-12-31    45.80
 41277  16779755770  4324911048 2016-12-31   119.00

 [41278 rows x 4 columns],
 '2017':               会员ID         订单号       提交日期    订单金额
 0      38765290840  4324911135 2017-01-01  1799.0
 1      39305832102  4324911213 2017-01-01   369.0
 2      34190994969  4324911251 2017-01-01   189.0
 3      38986333210  4324911283 2017-01-01   169.0
 4          4271359  4324911355 2017-01-01    78.0
 ...            ...         ...        ...     ...
 50834  39155833075  4338762307 2017-12-31    96.0
 50835  29523124076  4338762514 2017-12-31    99.0
 50836      7807573  4338762906 2017-12-31   258.0
 50837  36642530033  4338762958 2017-12-31   286.0
 50838  39155901156  4338763879 2017-12-31   249.0

 [50839 rows x 4 columns],
 '2018':               会员ID         订单号       提交日期    订单金额
 0      39229691808  4338764262 2018-01-01  3646.0
 1      39293668916  4338764363 2018-01-01  3999.0
 2      35059646224  4338764376 2018-01-01    10.1
 3          1084397  4338770013 2018-01-01   828.0
 4          3349915  4338770121 2018-01-01  3758.0
 ...            ...         ...        ...     ...
 81344  39229485704  4354225182 2018-12-31   249.0
 81345  39229021075  4354225188 2018-12-31    89.0
 81346  39288976750  4354230034 2018-12-31    48.5
 81347     26772630  4354230163 2018-12-31  3196.0
 81348  39455580335  4354235084 2018-12-31  2999.0

 [81349 rows x 4 columns],
 '会员等级':                会员ID  会员等级
 0            100090     3
 1       10012905801     1
 2       10012935109     1
 3       10013498043     1
 4       10014087899     4
 ...             ...   ...
 154380       998138     3
 154381       998298     1
 154382       998571     4
 154383       999563     4
 154384       999951     1

 [154385 rows x 2 columns]}

In [62]:
# 1.3 查看 sheet_dict 变量的数据类型
type(sheet_dict)
# 1.4 查看2015 Excel表的DataFrame对象
sheet_dict['2015']

# 1.5 查看2015 Excel表的DataFrame对象的 基本信息
sheet_dict['2015'].info()
# 1.6 查看2015 Excel表的DataFrame对象的 基本统计信息
sheet_dict['2015'].describe()

<class 'pandas.DataFrame'>
RangeIndex: 30774 entries, 0 to 30773
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   会员ID    30774 non-null  int64
 1   订单号     30774 non-null  int64
 2   提交日期    30774 non-null  datetime64[us]
 3   订单金额    30774 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(2)
memory usage: 961.8 KB

               会员ID           订单号                        提交日期           订单金额
count  3.077400e+04  3.077400e+04                       30774   30774.000000
mean   2.918779e+10  4.020414e+09  2015-07-01 20:55:49.424839     960.991161
min    2.670000e+02  3.000305e+09         2015-01-01 00:00:00       0.500000
25%    1.944122e+10  3.885510e+09         2015-04-02 00:00:00      59.000000
50%    3.746545e+10  4.117491e+09         2015-07-02 00:00:00     139.000000
75%    3.923593e+10  4.234882e+09         2015-10-01 00:00:00     899.000000
max    3.954613e+10  4.282025e+09         2015-12-31 00:00:00  111750.000000
std    1.385333e+10  2.630510e+08                         NaN    2068.107231

In [63]:
# 1.7 查看字典中每个df对象(即：每张sheet表)的基本信息 和统计信息
for i in sheet_names:
    print(i)   # i ---> 每个sheet表名
    print(sheet_dict[i].info())
    print(sheet_dict[i].describe())

2015
<class 'pandas.DataFrame'>
RangeIndex: 30774 entries, 0 to 30773
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   会员ID    30774 non-null  int64
 1   订单号     30774 non-null  int64
 2   提交日期    30774 non-null  datetime64[us]
 3   订单金额    30774 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(2)
memory usage: 961.8 KB
None
               会员ID           订单号                        提交日期           订单金额
count  3.077400e+04  3.077400e+04                       30774   30774.000000
mean   2.918779e+10  4.020414e+09  2015-07-01 20:55:49.424839     960.991161
min    2.670000e+02  3.000305e+09         2015-01-01 00:00:00       0.500000
25%    1.944122e+10  3.885510e+09         2015-04-02 00:00:00      59.000000
50%    3.746545e+10  4.117491e+09         2015-07-02 00:00:00     139.000000
75%    3.923593e+10  4.234882e+09         2015-10-01 00:00:00     899.000000
max    3.954613e+10  4.282025e+09         2015-12-31 00:00:00  111750.000000
std    1.385333e+10  2.630510e+08                         NaN    2068.107231
2016
<class 'pandas.DataFrame'>
RangeIndex: 41278 entries, 0 to 41277
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   会员ID    41278 non-null  int64
 1   订单号     41278 non-null  int64
 2   提交日期    41278 non-null  datetime64[us]
 3   订单金额    41277 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(2)
memory usage: 1.3 MB
None
               会员ID           订单号                        提交日期           订单金额
count  4.127800e+04  4.127800e+04                       41278   41277.000000
mean   2.908415e+10  4.313583e+09  2016-07-01 16:34:58.008624     957.106694
min    8.100000e+01  4.282026e+09         2016-01-01 00:00:00       0.100000
25%    1.934990e+10  4.309457e+09         2016-04-01 00:00:00      59.000000
50%    3.730339e+10  4.317545e+09         2016-07-02 00:00:00     147.000000
75%    3.923182e+10  4.321132e+09         2016-10-01 00:00:00     888.000000
max    3.954554e+10  4.324911e+09         2016-12-31 00:00:00  174900.000000
std    1.389468e+10  1.094572e+07                         NaN    2478.560036
2017
<class 'pandas.DataFrame'>
RangeIndex: 50839 entries, 0 to 50838
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   会员ID    50839 non-null  int64
 1   订单号     50839 non-null  int64
 2   提交日期    50839 non-null  datetime64[us]
 3   订单金额    50839 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(2)
memory usage: 1.6 MB
None
               会员ID           订单号                        提交日期           订单金额
count  5.083900e+04  5.083900e+04                       50839   50839.000000
mean   2.882368e+10  4.332466e+09  2017-07-02 00:53:06.530026     963.587872
min    2.780000e+02  4.324911e+09         2017-01-01 00:00:00       0.300000
25%    1.869274e+10  4.328415e+09         2017-04-01 00:00:00      59.000000
50%    3.688044e+10  4.331989e+09         2017-07-02 00:00:00     149.000000
75%    3.923020e+10  4.337515e+09         2017-10-02 00:00:00     898.000000
max    3.954554e+10  4.338764e+09         2017-12-31 00:00:00  123609.000000
std    1.409416e+10  4.404350e+06                         NaN    2178.727261
2018
<class 'pandas.DataFrame'>
RangeIndex: 81349 entries, 0 to 81348
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   会员ID    81349 non-null  int64
 1   订单号     81349 non-null  int64
 2   提交日期    81349 non-null  datetime64[us]
 3   订单金额    81348 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(2)
memory usage: 2.5 MB
None
               会员ID           订单号                        提交日期           订单金额
count  8.134900e+04  8.134900e+04                       81349   81348.000000
mean   2.902317e+10  4.348372e+09  2018-07-01 17:23:17.489828     966.582792
min    2.780000e+02  4.338764e+09         2018-01-01 00:00:00       0.000000
25%    1.902755e+10  4.345654e+09         2018-04-01 00:00:00      60.000000
50%    3.740121e+10  4.349448e+09         2018-07-01 00:00:00     149.000000
75%    3.923380e+10  4.351639e+09         2018-10-01 00:00:00     899.000000
max    3.954614e+10  4.354235e+09         2018-12-31 00:00:00  174900.000000
std    1.404116e+10  4.183774e+06                         NaN    2204.969534
会员等级
<class 'pandas.DataFrame'>
RangeIndex: 154385 entries, 0 to 154384
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   会员ID    154385 non-null  int64
 1   会员等级    154385 non-null  int64
dtypes: int64(2)
memory usage: 2.4 MB
None
               会员ID           会员等级
count  1.543850e+05  154385.000000
mean   2.980055e+10       2.259701
std    1.365654e+10       1.346408
min    8.100000e+01       1.000000
25%    2.213894e+10       1.000000
50%    3.833022e+10       2.000000
75%    3.927932e+10       3.000000
max    3.954614e+10       5.000000

### 2. 数据的预处理

In [64]:
# 需要处理的动作：1.删除缺失值。2. 过滤出金额 > 1的订单。3.固定时间节点，以每年的最后一天作为当年的分析节点。
# 1. 遍历，获取每张表(除了最后1张)
for i in sheet_names[:-1]:
    # print(i)  # i ---> 每个sheet表名 2015,2016,2017, 2018
    # 2. 删除缺失值
    sheet_dict[i] = sheet_dict[i].dropna()
    # 3. 筛选金额 > 1的订单
    sheet_dict[i] = sheet_dict[i][sheet_dict[i]['订单金额'] > 1]
    # sheet_dict[i] = sheet_dict[i].query('订单金额 > 1')
    # 4. 固定时间节点，以每年最后1天当做当年的 分析节点
    sheet_dict[i]['max_year_date'] = sheet_dict[i]['提交日期'].max()

# 5.查看处理后的数据
for i in sheet_names:
    print(i)
    print(sheet_dict[i].info())
    print(sheet_dict[i].describe())

2015
<class 'pandas.DataFrame'>
Index: 30574 entries, 0 to 30773
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   会员ID           30574 non-null  int64
 1   订单号            30574 non-null  int64
 2   提交日期           30574 non-null  datetime64[us]
 3   订单金额           30574 non-null  float64
 4   max_year_date  30574 non-null  datetime64[us]
dtypes: datetime64[us](2), float64(1), int64(2)
memory usage: 1.4 MB
None
               会员ID           订单号                        提交日期           订单金额  \
count  3.057400e+04  3.057400e+04                       30574   30574.000000
mean   2.921327e+10  4.020442e+09  2015-07-01 21:10:04.042650     967.270965
min    2.670000e+02  3.000305e+09         2015-01-01 00:00:00       1.500000
25%    1.961657e+10  3.885746e+09         2015-04-02 00:00:00      59.700000
50%    3.754532e+10  4.117491e+09         2015-07-02 00:00:00     142.000000
75%    3.923630e+10  4.234853e+09         2015-10-01 00:00:00     899.000000
max    3.954613e+10  4.282025e+09         2015-12-31 00:00:00  111750.000000
std    1.384598e+10  2.630518e+08                         NaN    2073.397861

             max_year_date
count                30574
mean   2015-12-31 00:00:00
min    2015-12-31 00:00:00
25%    2015-12-31 00:00:00
50%    2015-12-31 00:00:00
75%    2015-12-31 00:00:00
max    2015-12-31 00:00:00
std                    NaN
2016
<class 'pandas.DataFrame'>
Index: 41001 entries, 0 to 41277
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   会员ID           41001 non-null  int64
 1   订单号            41001 non-null  int64
 2   提交日期           41001 non-null  datetime64[us]
 3   订单金额           41001 non-null  float64
 4   max_year_date  41001 non-null  datetime64[us]
dtypes: datetime64[us](2), float64(1), int64(2)
memory usage: 1.9 MB
None
               会员ID           订单号                        提交日期           订单金额  \
count  4.100100e+04  4.100100e+04                       41001   41001.000000
mean   2.910772e+10  4.313582e+09  2016-07-01 16:37:53.739665     963.542790
min    8.100000e+01  4.282026e+09         2016-01-01 00:00:00       1.500000
25%    1.943201e+10  4.309457e+09         2016-04-01 00:00:00      65.000000
50%    3.740237e+10  4.317545e+09         2016-07-02 00:00:00     149.000000
75%    3.923184e+10  4.321133e+09         2016-10-01 00:00:00     898.000000
max    3.954554e+10  4.324911e+09         2016-12-31 00:00:00  174900.000000
std    1.388571e+10  1.094832e+07                         NaN    2485.642632

             max_year_date
count                41001
mean   2016-12-31 00:00:00
min    2016-12-31 00:00:00
25%    2016-12-31 00:00:00
50%    2016-12-31 00:00:00
75%    2016-12-31 00:00:00
max    2016-12-31 00:00:00
std                    NaN
2017
<class 'pandas.DataFrame'>
Index: 50451 entries, 0 to 50838
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   会员ID           50451 non-null  int64
 1   订单号            50451 non-null  int64
 2   提交日期           50451 non-null  datetime64[us]
 3   订单金额           50451 non-null  float64
 4   max_year_date  50451 non-null  datetime64[us]
dtypes: datetime64[us](2), float64(1), int64(2)
memory usage: 2.3 MB
None
               会员ID           订单号                        提交日期           订单金额  \
count  5.045100e+04  5.045100e+04                       50451   50451.000000
mean   2.884214e+10  4.332469e+09  2017-07-02 02:16:12.301837     970.990793
min    2.780000e+02  4.324911e+09         2017-01-01 00:00:00       1.500000
25%    1.870549e+10  4.328416e+09         2017-04-01 00:00:00      65.000000
50%    3.692362e+10  4.331989e+09         2017-07-02 00:00:00     155.000000
75%    3.923070e+10  4.337528e+09         2017-10-02 00:00:00     899.000000
max    3.954554e+10  4.338764e+09         2017-12-31 00:00:00  123609.000000
std    1.408666e+10  4.404894e+06                         NaN    2185.446995

             max_year_date
count                50451
mean   2017-12-31 00:00:00
min    2017-12-31 00:00:00
25%    2017-12-31 00:00:00
50%    2017-12-31 00:00:00
75%    2017-12-31 00:00:00
max    2017-12-31 00:00:00
std                    NaN
2018
<class 'pandas.DataFrame'>
Index: 80801 entries, 0 to 81348
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   会员ID           80801 non-null  int64
 1   订单号            80801 non-null  int64
 2   提交日期           80801 non-null  datetime64[us]
 3   订单金额           80801 non-null  float64
 4   max_year_date  80801 non-null  datetime64[us]
dtypes: datetime64[us](2), float64(1), int64(2)
memory usage: 3.7 MB
None
               会员ID           订单号                        提交日期           订单金额  \
count  8.080100e+04  8.080100e+04                       80801   80801.000000
mean   2.905571e+10  4.348372e+09  2018-07-01 18:16:22.948230     973.119528
min    2.780000e+02  4.338764e+09         2018-01-01 00:00:00       1.500000
25%    1.919622e+10  4.345654e+09         2018-04-01 00:00:00      68.000000
50%    3.749326e+10  4.349448e+09         2018-07-01 00:00:00     151.700000
75%    3.923398e+10  4.351641e+09         2018-10-02 00:00:00     925.000000
max    3.954614e+10  4.354235e+09         2018-12-31 00:00:00  174900.000000
std    1.402185e+10  4.185250e+06                         NaN    2210.983968

             max_year_date
count                80801
mean   2018-12-31 00:00:00
min    2018-12-31 00:00:00
25%    2018-12-31 00:00:00
50%    2018-12-31 00:00:00
75%    2018-12-31 00:00:00
max    2018-12-31 00:00:00
std                    NaN
会员等级
<class 'pandas.DataFrame'>
RangeIndex: 154385 entries, 0 to 154384
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   会员ID    154385 non-null  int64
 1   会员等级    154385 non-null  int64
dtypes: int64(2)
memory usage: 2.4 MB
None
               会员ID           会员等级
count  1.543850e+05  154385.000000
mean   2.980055e+10       2.259701
std    1.365654e+10       1.346408
min    8.100000e+01       1.000000
25%    2.213894e+10       1.000000
50%    3.833022e+10       2.000000
75%    3.927932e+10       3.000000
max    3.954614e+10       5.000000

In [65]:
# 6. 把上述的4张表(对应的4个df对象), 合并成一个df对象
type(list(sheet_dict.values())[:-1])  # list类型: [df对象, df对象, df对象, df对象] ->前4张表
df_merge = pd.concat(list(sheet_dict.values())[:-1], ignore_index=True) # 合并并重置索引
df_merge

               会员ID         订单号       提交日期    订单金额 max_year_date
0       15278002468  3000304681 2015-01-01   499.0    2015-12-31
1       39236378972  3000305791 2015-01-01  2588.0    2015-12-31
2       38722039578  3000641787 2015-01-01   498.0    2015-12-31
3       11049640063  3000798913 2015-01-01  1572.0    2015-12-31
4       35038752292  3000821546 2015-01-01    10.1    2015-12-31
...             ...         ...        ...     ...           ...
202822  39229485704  4354225182 2018-12-31   249.0    2018-12-31
202823  39229021075  4354225188 2018-12-31    89.0    2018-12-31
202824  39288976750  4354230034 2018-12-31    48.5    2018-12-31
202825     26772630  4354230163 2018-12-31  3196.0    2018-12-31
202826  39455580335  4354235084 2018-12-31  2999.0    2018-12-31

[202827 rows x 5 columns]

In [66]:
# 7. 为了好区分，给df对象新增 year列
df_merge['year'] = df_merge['提交日期'].dt.year
df_merge

               会员ID         订单号       提交日期    订单金额 max_year_date  year
0       15278002468  3000304681 2015-01-01   499.0    2015-12-31  2015
1       39236378972  3000305791 2015-01-01  2588.0    2015-12-31  2015
2       38722039578  3000641787 2015-01-01   498.0    2015-12-31  2015
3       11049640063  3000798913 2015-01-01  1572.0    2015-12-31  2015
4       35038752292  3000821546 2015-01-01    10.1    2015-12-31  2015
...             ...         ...        ...     ...           ...   ...
202822  39229485704  4354225182 2018-12-31   249.0    2018-12-31  2018
202823  39229021075  4354225188 2018-12-31    89.0    2018-12-31  2018
202824  39288976750  4354230034 2018-12-31    48.5    2018-12-31  2018
202825     26772630  4354230163 2018-12-31  3196.0    2018-12-31  2018
202826  39455580335  4354235084 2018-12-31  2999.0    2018-12-31  2018

[202827 rows x 6 columns]

In [67]:
# 8. 给表新增1列， date_interval 表示 本订单购买时间 距 统计节点时间的 差值
df_merge['date_interval'] = df_merge['max_year_date'] - df_merge['提交日期']
# 把 date_interval列的数据类型改为int
df_merge['date_interval'] = df_merge['date_interval'].dt.days
print(df_merge)

               会员ID         订单号       提交日期    订单金额 max_year_date  year  \
0       15278002468  3000304681 2015-01-01   499.0    2015-12-31  2015
1       39236378972  3000305791 2015-01-01  2588.0    2015-12-31  2015
2       38722039578  3000641787 2015-01-01   498.0    2015-12-31  2015
3       11049640063  3000798913 2015-01-01  1572.0    2015-12-31  2015
4       35038752292  3000821546 2015-01-01    10.1    2015-12-31  2015
...             ...         ...        ...     ...           ...   ...
202822  39229485704  4354225182 2018-12-31   249.0    2018-12-31  2018
202823  39229021075  4354225188 2018-12-31    89.0    2018-12-31  2018
202824  39288976750  4354230034 2018-12-31    48.5    2018-12-31  2018
202825     26772630  4354230163 2018-12-31  3196.0    2018-12-31  2018
202826  39455580335  4354235084 2018-12-31  2999.0    2018-12-31  2018

        date_interval
0                 364
1                 364
2                 364
3                 364
4                 364
...               ...
202822              0
202823              0
202824              0
202825              0
202826              0

[202827 rows x 7 columns]

### 3. 数据的统计分析

In [68]:
# 1. 基于year 和 会员ID分组，统计：REM三项的基本数据
# 回顾： REM： recency(最近一次购买时间), frequency(购买次数), monetary(购买金额)
rfm_gb = df_merge.groupby(['year', '会员ID'], as_index=False).agg({
    'date_interval': 'min',
    '订单号': 'count',
    '订单金额': 'sum'
})
print(rfm_gb)

        year         会员ID  date_interval  订单号    订单金额
0       2015          267            197    2   105.0
1       2015          282            251    1    29.7
2       2015          283            340    1  5398.0
3       2015          343            300    1   118.0
4       2015          525             37    3   213.0
...      ...          ...            ...  ...     ...
148586  2018  39538034299            272    1    49.0
148587  2018  39538034662            189    1  3558.0
148588  2018  39538035729            179    1  3699.0
148589  2018  39545237824            275    1    49.0
148590  2018  39546136285            163    1    19.9

[148591 rows x 5 columns]

In [69]:
# 2.修改列名
rfm_gb.columns = ['year', '会员ID', 'r', 'f', 'm']
print(rfm_gb)

        year         会员ID    r  f       m
0       2015          267  197  2   105.0
1       2015          282  251  1    29.7
2       2015          283  340  1  5398.0
3       2015          343  300  1   118.0
4       2015          525   37  3   213.0
...      ...          ...  ... ..     ...
148586  2018  39538034299  272  1    49.0
148587  2018  39538034662  189  1  3558.0
148588  2018  39538035729  179  1  3699.0
148589  2018  39545237824  275  1    49.0
148590  2018  39546136285  163  1    19.9

[148591 rows x 5 columns]

In [70]:
# 3. 分别查看下 r, f, m 这3列值的分布情况
# rfm_gb.iloc[:,2:].describe().T
print(rfm_gb.iloc[:,2:].describe().T)

      count         mean          std  min   25%    50%     75%       max
r  148591.0   165.524043   101.988472  0.0  79.0  156.0   255.0     365.0
f  148591.0     1.365002     2.626953  1.0   1.0    1.0     1.0     130.0
m  148591.0  1323.741329  3753.906883  1.5  69.0  189.0  1199.0  206251.8

In [71]:
# 4. 划分区间，分别给出 RFM的评分，依据：r：最近一次购买时间，越小分越高，f:购买次数， 越大分越高， m：购买金额 越大分越高
# 思路1：我们给定区间数，由系统自动划分区间范围
pd.cut(rfm_gb['r'], bins=3).unique() # [(121.667, 243.333], (243.333, 365.0], (-0.365, 121.667]] 包右不包左
# 思路2：我们给定区间范围，由系统自动划分区间数(注意：包右不包左)
r_bins = [-1, 79, 255, 365]  # min, 25% 75% max
f_bins = [-1, 79, 255, 365]  # min, 25% 75% max
m_bins = [1, 69, 1199, 206252]  # min, 25% 75% max

pd.cut(rfm_gb['r'], bins=r_bins).unique()

[(79, 255], (255, 365], (-1, 79]]
Categories (3, interval[int64, right]): [(-1, 79] < (79, 255] < (255, 365]]

In [72]:
# 思路3：基于我们手动制动区间范围，给出每个范围 的 评分(三分法：低中高)
rfm_gb['r_label'] = pd.cut(rfm_gb['r'], bins=r_bins, labels=[3, 2, 1]) # r值(最近购买时间)越小，分越高
rfm_gb['f_label'] = pd.cut(rfm_gb['f'], bins=f_bins, labels=[1, 2, 3]) # f值(购买次数)越大，分越高
rfm_gb['m_label'] = pd.cut(rfm_gb['m'], bins=m_bins, labels=[1, 2, 3]) # m值(购买金额)越大，分越高
print(rfm_gb)

        year         会员ID    r  f       m r_label f_label m_label
0       2015          267  197  2   105.0       2       1       2
1       2015          282  251  1    29.7       2       1       1
2       2015          283  340  1  5398.0       1       1       3
3       2015          343  300  1   118.0       1       1       2
4       2015          525   37  3   213.0       3       1       2
...      ...          ...  ... ..     ...     ...     ...     ...
148586  2018  39538034299  272  1    49.0       1       1       1
148587  2018  39538034662  189  1  3558.0       2       1       3
148588  2018  39538035729  179  1  3699.0       2       1       3
148589  2018  39545237824  275  1    49.0       1       1       1
148590  2018  39546136285  163  1    19.9       2       1       1

[148591 rows x 8 columns]

In [73]:
# 实际开发写法，完整版
# 思路4：基于我们手动指定区间范围，给出每个范围的评分(三分法，低中高)
# r值(最近购买时间)越小，分越高
rfm_gb['r_label'] = pd.cut(rfm_gb['r'], bins=r_bins, labels=[i for i in range(len(r_bins) - 1, 0, -1)])
# f值(购买次数)越大，分越高
rfm_gb['f_label'] = pd.cut(rfm_gb['f'], bins=f_bins, labels=[i for i in range(1, len(f_bins))])
# m值(购买金额)越大，分越高
rfm_gb['m_label'] = pd.cut(rfm_gb['m'], bins=m_bins, labels=[i for i in range(1, len(m_bins))])
print(rfm_gb)

        year         会员ID    r  f       m r_label f_label m_label
0       2015          267  197  2   105.0       2       1       2
1       2015          282  251  1    29.7       2       1       1
2       2015          283  340  1  5398.0       1       1       3
3       2015          343  300  1   118.0       1       1       2
4       2015          525   37  3   213.0       3       1       2
...      ...          ...  ... ..     ...     ...     ...     ...
148586  2018  39538034299  272  1    49.0       1       1       1
148587  2018  39538034662  189  1  3558.0       2       1       3
148588  2018  39538035729  179  1  3699.0       2       1       3
148589  2018  39545237824  275  1    49.0       1       1       1
148590  2018  39546136285  163  1    19.9       2       1       1

[148591 rows x 8 columns]

In [74]:
# 5. 统计每个会员的 RFM的评。 采取方案 --> 拼接
rfm_gb.r_label  # 查看类型
# step1: 转换类型，把 r_label, f_label, m_label 从 Categories分类类型 转换成 字符串类型
rfm_gb['r_label'] = rfm_gb['r_label'].astype(str)
rfm_gb['f_label'] = rfm_gb['f_label'].astype(str)
rfm_gb['m_label'] = rfm_gb['m_label'].astype(str)

# step2: 拼接评分
rfm_gb['rfm_group'] = rfm_gb['r_label'] + rfm_gb['f_label'] + rfm_gb['m_label']
print(rfm_gb)

        year         会员ID    r  f       m r_label f_label m_label rfm_group
0       2015          267  197  2   105.0       2       1       2       212
1       2015          282  251  1    29.7       2       1       1       211
2       2015          283  340  1  5398.0       1       1       3       113
3       2015          343  300  1   118.0       1       1       2       112
4       2015          525   37  3   213.0       3       1       2       312
...      ...          ...  ... ..     ...     ...     ...     ...       ...
148586  2018  39538034299  272  1    49.0       1       1       1       111
148587  2018  39538034662  189  1  3558.0       2       1       3       213
148588  2018  39538035729  179  1  3699.0       2       1       3       213
148589  2018  39545237824  275  1    49.0       1       1       1       111
148590  2018  39546136285  163  1    19.9       2       1       1       211

[148591 rows x 9 columns]

### 4. 导出数据

In [75]:
# 1. 导出结果到Excel文件中，忽略索引
rfm_gb.to_excel('./data/sale_rfm_group.xlsx', index=False)

In [76]:
# 2. 导出结果到mysql表中
# 2.1 创建引擎对象
engine = create_engine('mysql+pymysql://root:123456@127.0.0.1:3306/rfm_db?charset=utf8')
# 2.2 具体的导出数据到MySQL表中
# 参1： 存储结果的数据表名称
# 参2： 引擎对象
# 参3： 忽略索引
# 参4： 如果表存在，则替换数据
rfm_gb.to_sql('rfm_table', engine, index=False, if_exists='replace')
# 2.3 查看数据
pd.read_sql('select * from rfm_table', engine)

148591

### 5. 数据可视化

In [77]:
# 5.1 准备可视化的数据，即：rfm_group(分组结果评分)，year(统计年份), number(评分个数)
display_data = rfm_gb.groupby(['rfm_group','year'], as_index=False).agg({'会员ID': 'count'})
print(display_data)

   rfm_group  year   会员ID
0        111  2015   2180
1        111  2016   1498
2        111  2017   3170
3        111  2018   2279
4        112  2015   3838
5        112  2016   2958
6        112  2017   5749
7        112  2018   5318
8        113  2015   1824
9        113  2016   1519
10       113  2017   2546
11       113  2018   4039
12       123  2016     11
13       211  2015   3534
14       211  2016   4684
15       211  2017   3512
16       211  2018   7317
17       212  2015   6619
18       212  2016   9056
19       212  2017   7029
20       212  2018  14522
21       213  2015   3019
22       213  2016   4128
23       213  2017   3610
24       213  2018   7029
25       311  2015   1724
26       311  2016   2180
27       311  2017   2167
28       311  2018   3238
29       312  2015   3374
30       312  2016   4532
31       312  2017   4391
32       312  2018   6805
33       313  2015   1499
34       313  2016   2039
35       313  2017   2093
36       313  2018   3560
37       323  2018      1

In [78]:
# 5.2 修改列名
display_data.columns=['rfm_group', 'year', 'number']
# 细节:把rfm_group列的数据类型改为int
display_data['rfm_group'] = display_data['rfm_group'].astype(int)
print(display_data)

    rfm_group  year  number
0         111  2015    2180
1         111  2016    1498
2         111  2017    3170
3         111  2018    2279
4         112  2015    3838
5         112  2016    2958
6         112  2017    5749
7         112  2018    5318
8         113  2015    1824
9         113  2016    1519
10        113  2017    2546
11        113  2018    4039
12        123  2016      11
13        211  2015    3534
14        211  2016    4684
15        211  2017    3512
16        211  2018    7317
17        212  2015    6619
18        212  2016    9056
19        212  2017    7029
20        212  2018   14522
21        213  2015    3019
22        213  2016    4128
23        213  2017    3610
24        213  2018    7029
25        311  2015    1724
26        311  2016    2180
27        311  2017    2167
28        311  2018    3238
29        312  2015    3374
30        312  2016    4532
31        312  2017    4391
32        312  2018    6805
33        313  2015    1499
34        313  2016    2039
35        313  2017    2093
36        313  2018    3560
37        323  2018       1

In [79]:
# 5.3 绘制图形

# 颜色池
range_color = ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf',
               '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026']

range_max = int(display_data['number'].max())
c = (
    Bar3D()#设置了一个3D柱形图对象
    .add(
        "",#图例
        [d.tolist() for d in display_data.values],#数据
        xaxis3d_opts=opts.Axis3DOpts(type_="category", name='分组名称'),#x轴数据类型，名称，rfm_group
        yaxis3d_opts=opts.Axis3DOpts(type_="category", name='年份'),#y轴数据类型，名称，year
        zaxis3d_opts=opts.Axis3DOpts(type_="value", name='会员数量'),#z轴数据类型，名称，number
    )
    .set_global_opts( # 全局设置
        visualmap_opts=opts.VisualMapOpts(max_=range_max, range_color=range_color), #设置颜色，及不同取值对应的颜色
        title_opts=opts.TitleOpts(title="RFM分组结果"),#设置标题
    )
)
c.render() 		      # 数据保存到本地的网页中.
# c.render_notebook() #在notebook中显示

'/Users/shangrongli/Documents/my-workspace/PythonProject/pyDataAnalysis/render.html'